### ISSUE TITLE
Problem with Filter

### ISSUE THREAD

**Issue by marvink** [sbt/sbt-concat#11] opened 2014-10-10 16:58 UTC
Hi, i tried to get this plugin working but it seems to be that only the way via Pathfinders is working:
I use sbt-concat with the play framework, which is quite standard configured. As i debugged the code i saw that the if (mapping.nonEmpty) { is always false. Maybe you can have a look at this and help me. :-)

```
//includeFilter in concat := GlobFilter("app/assets/js/*.js")

Concat.parentDir := "/js/"

Concat.groups := Seq(
  "modernizr.js" -> group((baseDirectory.value / "app" / "assets" / "js" / "modernizr") * "*.js"),
  "main.js" -> group(Seq("app/assets/js/plugin.js", "app/assets/js/main.js"))
)

pipelineStages in Assets := Seq(concat)
```

I am new in Scala and i have no clue what this is doing. Looks like magic. In past you would be burnt at the stake. :+1: 

```
val filteredMappings = mappings.filter(m => (includeFilter in concat).value.accept(m._1) && m._1.isFile)
```

**Comment by mkurz** [comment] 2024-01-11 23:10
Basically a duplicate of
- #21

**Closed by mkurz** 2024-01-11 23:10 UTC
